# Generated by Django 4.2.8 on 2023-12-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='psw',
            new_name='password',
        ),
    ]
