# Generated by Django 4.2.8 on 2024-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
